"""add provider_list_id to tasks

Revision ID: c14a440f8b8b
Revises: 31548f31a054
Create Date: 2026-07-19 20:53:04.734947

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14a440f8b8b'
down_revision: str | None = '31548f31a054'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('provider_list_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'provider_list_id')
    # ### end Alembic commands ###
