"""add provider_list_name to tasks

Revision ID: d3290a38091b
Revises: c14a440f8b8b
Create Date: 2026-07-19 21:17:07.964391

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3290a38091b'
down_revision: str | None = 'c14a440f8b8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('provider_list_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'provider_list_name')
    # ### end Alembic commands ###
